### ISSUE TITLE
v3 fails to load

### ISSUE THREAD

**Issue by djbrown** [paambaati/codeclimate-action#638] opened 2022-12-22 17:45 UTC
I just upgraded from `v3.0.0` to `v3` which currently should be `v3.2.0`.
See commit https://github.com/djbrown/hbscorez/commit/8cd91851cd03862794e8138c028a5f175ea4ddd9#diff-68ba9d12f6f2601fe3c9f7f9d0d02aaea52384559d6d08fae7afc941663fdfcdR89 file `.github/workflows/ci-build.yml` Line 89
Before:
```yaml
      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
```
After:
```yaml
      - uses: paambaati/codeclimate-action@v3
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
```
But then my workflow step aborts with following error:
```
Download action repository 'paambaati/codeclimate-action@v3' (SHA:e5d7b870aec2c3faa8249ec2444850f153c6ccef)
Error: paambaati/codeclimate-action/v3/action.yml:
Error: paambaati/codeclimate-action/v3/action.yml: (Line: 30, Col: 51, Idx: 902) - (Line: 30, Col: 80, Idx: 931): While parsing a block mapping, did not find expected key.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load paambaati/codeclimate-action/v3/action.yml
```

Just as in https://github.com/paambaati/codeclimate-action/issues/430 (v3.0.0 fails to load)

**Comment by djbrown** [comment] 2022-12-22 17:47
I just rerun my workflow, but the problem still persists

**Comment by djbrown** [comment] 2022-12-22 18:05
So I just set the version explicitly to `v3.2.0` and that works!
But the problem with `v3` still persists.
Priority for me is lower now :) but I still looked into it.
the hash of the downloadad action points to https://github.com/paambaati/codeclimate-action/commit/e5d7b870aec2c3faa8249ec2444850f153c6ccef aka 3.1.0
the commit is from september 2021, but the version was released on october 2022.
"vX" should always resolve to the latest version. can you fix that or ask github whats wrong there?

**Comment by paambaati** [comment] 2022-12-23 00:46
Duplicate of https://github.com/paambaati/codeclimate-action/issues/577

This action publishes only specific version tags, so v3 does not resolve to the latest version. This is more a convention that some projects follow and should not be a hard expectation.

This can possibly be fixed in v4.x.x.

**Closed by paambaati** 2022-12-23 00:46 UTC
Labels: duplicate
