### ISSUE TITLE
Error with 2.5.6

### ISSUE THREAD

**Issue by AshLePoney** [paambaati/codeclimate-action#150] opened 2020-04-12 02:30 UTC
Hey :vulcan_salute:

I encounter an error with version `2.5.6` which does not fail the job, even when trying to define a location no format is retrieved.
I don't really understand, I don't know where the problem comes from. I've downgrade the version to `2.5.0` to get it working.

The test reporter error:
https://github.com/codeclimate/test-reporter/blob/master/cmd/format-coverage.go#L86

Invalid build  `2.5.6`:
https://github.com/AshLePoney/node-assert-enhanced/runs/579960704?check_suite_focus=true#step:6:117

Valid build with `2.5.0`:
https://github.com/AshLePoney/node-assert-enhanced/runs/579986479

Thanks

See ya, Ash

**Comment by paambaati** [comment] 2020-04-17 12:52
This is a duplicate of #119.

**Closed by paambaati** 2020-04-17 12:52 UTC
Labels: duplicate
