### ISSUE TITLE
action don't run the coverageCommand

### ISSUE THREAD

**Issue by lielran** [paambaati/codeclimate-action#237] opened 2020-10-01 05:46 UTC
**Describe the bug**
I tried to use the action but it seems not running the `command` 
the debug flag also doesn't show any more details 

**Version of `codeclimate-action` you're using**
`v2.7.1`

here is the usage part from my workflow file:
```
      - name: ✅ Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.1
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
        with:
          coverageCommand: yarn test:unit-coverage

```
the running result:
![Screen Shot 2020-10-01 at 8 45 32](https://user-images.githubusercontent.com/1004667/94772528-808a0600-03c2-11eb-9973-b06edf6de312.png)

**Comment by paambaati** [comment] 2020-10-01 05:48
@lielran Thanks for reporting this; this was _just_ fixes 45 minutes ago in [`v2.7.2`](https://github.com/paambaati/codeclimate-action/releases/tag/v2.7.2). Please try out that version and reopen this issue if the problem persists.

**Comment by paambaati** [comment] 2020-10-01 05:49
Duplicate of https://github.com/paambaati/codeclimate-action/issues/235

**Closed by paambaati** 2020-10-01 05:48 UTC
Labels: bug

**Comment by lielran** [comment] 2020-10-01 05:50
Thanks @paambaati  for the fastest reply ever :)

**Comment by lielran** [comment] 2020-10-01 05:53
Confirmed that v2.7.2 fixed the issue

**Comment by paambaati** [comment] 2020-10-01 05:55
@lielran ![](https://media1.tenor.com/images/565d24629787db02a347bcb54bd18d47/tenor.gif?itemid=11723956)
