### ISSUE TITLE
Error when downloading action

### ISSUE THREAD

**Issue by andresionek91** [paambaati/codeclimate-action#629] opened 2022-10-21 17:10 UTC
**Describe the bug**
Github actions cannot download the action when using `@v3` tag

```
Prepare all required actions
Getting action download info
Download action repository 'paambaati/codeclimate-action@v3' (SHA:e5d7b870aec[2](https://github.com/util-co/util-api-graphql/actions/runs/3299132738/jobs/5442142053#step:6:2)c[3](https://github.com/util-co/util-api-graphql/actions/runs/3299132738/jobs/5442142053#step:6:3)faa82[4](https://github.com/util-co/util-api-graphql/actions/runs/3299132738/jobs/5442142053#step:6:4)9ec2444850f153c6ccef)
Error: paambaati/codeclimate-action/v3/action.yml:
Error: paambaati/codeclimate-action/v3/action.yml: (Line: 30, Col: [5](https://github.com/util-co/util-api-graphql/actions/runs/3299132738/jobs/5442142053#step:6:5)1, Idx: 902) - (Line: 30, Col: 80, Idx: 931): While parsing a block mapping, did not find expected key.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load paambaati/codeclimate-action/v3/action.yml
```

**Version of `codeclimate-action` you're using**
`v3`

**Expected behavior**
Github should download and execute the action.

It works fine if specifying `@v3.2.0`.

**Comment by paambaati** [comment] 2022-10-21 18:03
Duplicate of https://github.com/paambaati/codeclimate-action/issues/626

**Closed by paambaati** 2022-10-21 18:03 UTC
Labels: bug

**Comment by andresionek91** [comment] 2022-10-22 07:42
I believe this is not a duplicate. Using the tag `@v3`  should be installing v3.2.2 and the bug should have been fixed.

**Comment by paambaati** [comment] 2022-10-23 03:02
There’s no published v3 version; you have to use fully specified version. So if you follow the examples, it should always be the latest, which is v3.2.0 at the time of writing.
