### ISSUE TITLE
[Bug] v3.0.0: could not find any viable formatter

### ISSUE THREAD

**Issue by selfagency** [paambaati/codeclimate-action#517] opened 2022-03-22 17:17 UTC
**Describe the bug**
The action says "could not find any viable formatter" when the formatter is explicitly provided.

**Version of `codeclimate-action` you're using**
`v3.0.0`

**Example links**
```
Run paambaati/codeclimate-action@v3.0.0
  with:
    coverageLocations:
      shared/coverage/lcov.info:lcov
      shared/coverage/**/lcov.info:lcov 
    debug: false
    verifyDownload: true
  env:
    CC_TEST_REPORTER_ID: 
/home/runner/work/unstoppable-domains-website/unstoppable-domains-website/cc-reporter before-build
ℹ️ 'coverageCommand' not set, so skipping building coverage report!
/home/runner/work/unstoppable-domains-website/unstoppable-domains-website/cc-reporter after-build --exit-code 0
Error: could not find any viable formatter. available formatters: clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, lcov-json, simplecov, xccov
Usage:
  cc-test-reporter after-build [flags]

Flags:
  -s, --batch-size int               batch size for source files (default 500)
  -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -t, --coverage-input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, lcov-json, simplecov, xccov]
      --exit-code int                exit code of the test run
  -r, --id string                    reporter identifier
      --insecure                     send coverage insecurely (without HTTPS)
  -p, --prefix string                the root directory where the coverage analysis was performed (default "/home/runner/work/unstoppable-domains-website/unstoppable-domains-website")

Global Flags:
  -d, --debug   run in debug mode

Error: The process '/home/runner/work/unstoppable-domains-website/unstoppable-domains-website/cc-reporter' failed with exit code [2](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5647938349?check_suite_focus=true#step:4:2)55
(node:1524) UnhandledPromiseRejectionWarning: Error: The process '/home/runner/work/unstoppable-domains-website/unstoppable-domains-website/cc-reporter' failed with exit code 255
    at ExecState._setResult (/home/runner/work/_actions/paambaati/codeclimate-action/v[3](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5647938349?check_suite_focus=true#step:4:3).0.0/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/paambaati/codeclimate-action/v3.0.0/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v3.0.0/node_modules/@actions/exec/lib/toolrunner.js:[4](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5647938349?check_suite_focus=true#step:4:4)69:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:[5](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5647938349?check_suite_focus=true#step:4:5))
(node:1524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1524) [DEP001[8](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5647938349?check_suite_focus=true#step:4:8)] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

my config is part of a private repo

**Expected behavior**
for the code coverage to be submitted

**Additional context**
n/a

**Comment by paambaati** [comment] 2022-03-23 06:19
@selfagency Please use the template – https://github.com/paambaati/codeclimate-action/issues/new/choose

This issue lacks any context (like links to failing run, steps to reproduce, etc.)

**Comment by ThomasKoppensteiner** [comment] 2022-04-27 12:03
I get a similar error.
Here is an example: https://github.com/ThomasKoppensteiner/sidekiq-undertaker/actions/runs/2232901840

**Comment by ThomasKoppensteiner** [comment] 2022-04-27 12:46
I could fix the above error by "passing the coverage data between jobs".
See https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow for details.

**Comment by ThomasKoppensteiner** [comment] 2022-04-27 14:09
Isn't this a duplicate of #316?

**Comment by paambaati** [comment] 2022-04-28 09:23
@ThomasKoppensteiner From the error, I can see that a coverage report was not found. And from your workflows, it looks like tests and coverage run as separate jobs.

@selfagency I'm closing this for now, as I'm assuming the failure is genuine as there's no coverage reports to actually upload. Please feel free to reopen with additional details if you'd like.

**Closed by paambaati** 2022-04-28 09:23 UTC
Labels: bug
